title: blog.phisch.codes

author:
  name: Philipp Schaffrath
  website: https://github.com/phisch

sass:
  sass_dir: _scss

baseurl: '/blog'
permalink: /:year/:day/:title

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  trail: 
    before: 2
    after: 2