title: blog.phisch.codes

author:
  name: Philipp Schaffrath
  website: https://github.com/phisch

baseurl: '/blog'
permalink: pretty

sass:
    sass_dir: _scss

compress_html:
  clippings: all

paginate: 5
paginate_path: "/page/:num/"