title: blog.phisch.codes

author:
  name: Philipp Schaffrath
  website: https://github.com/phisch

sass:
  sass_dir: _scss

baseurl: '/blog'
permalink: /:year/:day/:title

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  trail: 
    before: 2
    after: 2

giscus:
  enabled: true
  repository:
    name: "phisch/blog"
    id: "MDEwOlJlcG9zaXRvcnkzMzg2NDAwMTU="
  category:
    name: "Comments"
    id: "DIC_kwDOFC88j84B-k2z"
  mapping: "pathname"
  reactions: true
  emit_metadata: false
  theme: transparent_dark
  crossorigin: anonymous