title: blog.phisch.codes

author:
  name: Philipp Schaffrath
  website: https://github.com/phisch

baseurl: '/blog'
permalink: /:year/:day/:title

pagination:
  enabled: true
  sort_reverse: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  trail: 
    before: 2
    after: 2

sass:
  style: compressed
  sourcemap: development
  implementation: sass-embedded

giscus:
  enabled: true
  repository:
    name: "phisch/blog"
    id: "MDEwOlJlcG9zaXRvcnkzMzg2NDAwMTU="
  category:
    name: "Comments"
    id: "DIC_kwDOFC88j84B-k2z"
  mapping: "pathname"
  reactions: true
  emit_metadata: false
  theme: https://localhost:4000/blog/assets/styles/giscus.css
  crossorigin: anonymous

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: table
    wrap: false
    span:
      line_numbers: false

webrick:
  headers:
    Access-Control-Allow-Origin: "*"